src/Entity/Element.php
<?php

namespace App\Entity;

use App\Repository\ElementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ElementRepository::class)]
class Element
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $stock_restant;

    #[ORM\ManyToOne(targetEntity: Approvisionnement::class, inversedBy: 'elements')]
    #[ORM\JoinColumn(nullable: false)]
    private $approvisionnement;

    #[ORM\Column(type: 'string', length: 255)]
    private $UniteOeuvre;

    #[ORM\OneToMany(mappedBy: 'element', targetEntity: Mouvement::class)]
    private $mouvements;

    public function __construct()
    {
        $this->mouvements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getStockRestant(): ?int
    {
        return $this->stock_restant;
    }

    public function setStockRestant(int $stock_restant): self
    {
        $this->stock_restant = $stock_restant;

        return $this;
    }

    public function getApprovisionnement(): ?Approvisionnement
    {
        return $this->approvisionnement;
    }

    public function setApprovisionnement(?Approvisionnement $approvisionnement): self
    {
        $this->approvisionnement = $approvisionnement;

        return $this;
    }

    public function getUniteOeuvre(): ?string
    {
        return $this->UniteOeuvre;
    }

    public function setUniteOeuvre(string $UniteOeuvre): self
    {
        $this->UniteOeuvre = $UniteOeuvre;

        return $this;
    }

    /**
     * @return Collection<int, Mouvement>
     */
    public function getMouvements(): Collection
    {
        return $this->mouvements;
    }

    public function addMouvement(Mouvement $mouvement): self
    {
        if (!$this->mouvements->contains($mouvement)) {
            $this->mouvements[] = $mouvement;
            $mouvement->setElement($this);
        }

        return $this;
    }

    public function removeMouvement(Mouvement $mouvement): self
    {
        if ($this->mouvements->removeElement($mouvement)) {
            // set the owning side to null (unless already changed)
            if ($mouvement->getElement() === $this) {
                $mouvement->setElement(null);
            }
        }

        return $this;
    }
}

src/Entity/Observation.php
<?php

namespace App\Entity;

use App\Repository\ObservationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ObservationRepository::class)]
class Observation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $message;

    #[ORM\ManyToOne(targetEntity: Projet::class, inversedBy: 'observations')]
    #[ORM\JoinColumn(nullable: false)]
    private $projet;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date;

    #[ORM\Column(type: 'string', length: 255)]
    private $auteur;

    #[ORM\Column(type: 'string', length: 255)]
    private $poste;

    #[ORM\Column(type: 'integer')]
    private $user_id;

    public function __construct()
    {
        $this->date = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getProjet(): ?Projet
    {
        return $this->projet;
    }

    public function setProjet(?Projet $projet): self
    {
        $this->projet = $projet;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjetRepository::class)]
class Projet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'datetime')]
    private $demarrage;

    #[ORM\Column(type: 'integer')]
    private $delai;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $fin;

    #[ORM\Column(type: 'bigint')]
    private $budget;

    #[ORM\Column(type: 'boolean', nullable: true , options:["default"=>false])]
    private $est_termine;

    #[ORM\OneToOne(mappedBy: 'projet', targetEntity: Planning::class, cascade: ['persist', 'remove'])]
    private $planning;

    #[ORM\OneToOne(mappedBy: 'projet', targetEntity: Approvisionnement::class, cascade: ['persist', 'remove'])]
    private $approvisionnement;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'projets')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\OneToOne(mappedBy: 'projet', targetEntity: TauxExecFin::class, cascade: ['persist', 'remove'])]
    private $tauxExecFin;

    #[ORM\OneToOne(mappedBy: 'projet', targetEntity: TauxExecPhys::class, cascade: ['persist', 'remove'])]
    private $tauxExecPhys;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Observation::class)]
    private $observations;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Images::class)]
    private $images;

    #[ORM\Column(type: 'string', length: 255)]
    private $code;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Depense::class)]
    private $depenses;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Plan::class)]
    private $plans;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Presence::class)]
    private $presences;

    public function __construct()
    {
        $this->observations = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->depenses = new ArrayCollection();
        $this->demarrage = new DateTimeImmutable();
        $this->plans = new ArrayCollection();
        $this->demarrage = new DateTimeImmutable();
        $this->presences = new ArrayCollection();       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDemarrage(): ?\DateTimeInterface
    {
        return $this->demarrage;
    }

    public function setDemarrage(\DateTimeInterface $demarrage): self
    {
        $this->demarrage = $demarrage;

        return $this;
    }

    public function getDelai(): ?int
    {
        return $this->delai;
    }

    public function setDelai(int $delai): self
    {
        $this->delai = $delai;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(?\DateTimeInterface $fin): self
    {
        $this->fin = $fin;

        return $this;
    }

    public function getBudget(): ?string
    {
        return $this->budget;
    }

    public function setBudget(string $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getEstTermine(): ?bool
    {
        return $this->est_termine;
    }

    public function setEstTermine(?bool $est_termine): self
    {
        $this->est_termine = $est_termine;

        return $this;
    }

    public function getPlanning(): ?Planning
    {
        return $this->planning;
    }

    public function setPlanning(Planning $planning): self
    {
        // set the owning side of the relation if necessary
        if ($planning->getProjet() !== $this) {
            $planning->setProjet($this);
        }

        $this->planning = $planning;

        return $this;
    }

    public function getApprovisionnement(): ?Approvisionnement
    {
        return $this->approvisionnement;
    }

    public function setApprovisionnement(Approvisionnement $approvisionnement): self
    {
        // set the owning side of the relation if necessary
        if ($approvisionnement->getProjet() !== $this) {
            $approvisionnement->setProjet($this);
        }

        $this->approvisionnement = $approvisionnement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }

    public function getTauxExecFin(): ?TauxExecFin
    {
        return $this->tauxExecFin;
    }

    public function setTauxExecFin(TauxExecFin $tauxExecFin): self
    {
        // set the owning side of the relation if necessary
        if ($tauxExecFin->getProjet() !== $this) {
            $tauxExecFin->setProjet($this);
        }

        $this->tauxExecFin = $tauxExecFin;

        return $this;
    }

    public function getTauxExecPhys(): ?TauxExecPhys
    {
        return $this->tauxExecPhys;
    }

    public function setTauxExecPhys(TauxExecPhys $tauxExecPhys): self
    {
        // set the owning side of the relation if necessary
        if ($tauxExecPhys->getProjet() !== $this) {
            $tauxExecPhys->setProjet($this);
        }

        $this->tauxExecPhys = $tauxExecPhys;

        return $this;
    }

    /**
     * @return Collection<int, Observation>
     */
    public function getObservations(): Collection
    {
        return $this->observations;
    }

    public function addObservation(Observation $observation): self
    {
        if (!$this->observations->contains($observation)) {
            $this->observations[] = $observation;
            $observation->setProjet($this);
        }

        return $this;
    }

    public function removeObservation(Observation $observation): self
    {
        if ($this->observations->removeElement($observation)) {
            // set the owning side to null (unless already changed)
            if ($observation->getProjet() === $this) {
                $observation->setProjet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProjet($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProjet() === $this) {
                $image->setProjet(null);
            }
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return Collection<int, Depense>
     */
    public function getDepenses(): Collection
    {
        return $this->depenses;
    }

    public function addDepense(Depense $depense): self
    {
        if (!$this->depenses->contains($depense)) {
            $this->depenses[] = $depense;
            $depense->setProjet($this);
        }

        return $this;
    }

    public function removeDepense(Depense $depense): self
    {
        if ($this->depenses->removeElement($depense)) {
            // set the owning side to null (unless already changed)
            if ($depense->getProjet() === $this) {
                $depense->setProjet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Plan>
     */
    public function getPlans(): Collection
    {
        return $this->plans;
    }

    public function addPlan(Plan $plan): self
    {
        if (!$this->plans->contains($plan)) {
            $this->plans[] = $plan;
            $plan->setProjet($this);
        }

        return $this;
    }

    public function removePlan(Plan $plan): self
    {
        if ($this->plans->removeElement($plan)) {
            // set the owning side to null (unless already changed)
            if ($plan->getProjet() === $this) {
                $plan->setProjet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Presence>
     */
    public function getPresences(): Collection
    {
        return $this->presences;
    }

    public function addPresence(Presence $presence): self
    {
        if (!$this->presences->contains($presence)) {
            $this->presences[] = $presence;
            $presence->setProjet($this);
        }

        return $this;
    }

    public function removePresence(Presence $presence): self
    {
        if ($this->presences->removeElement($presence)) {
            // set the owning side to null (unless already changed)
            if ($presence->getProjet() === $this) {
                $presence->setProjet(null);
            }
        }

        return $this;
    }
}

src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TacheRepository::class)]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $intitule;

    #[ORM\Column(type: 'integer')]
    private $delai;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $debut_reel;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_fin;

    #[ORM\Column(type: 'boolean', nullable: true , options:['default' => false])]
    private $est_realise;

    #[ORM\ManyToOne(targetEntity: Planning::class, inversedBy: 'taches')]
    #[ORM\JoinColumn(nullable: false)]
    private $planning;

    #[ORM\Column(type: 'integer' , nullable:true)]
    private $delai_reel;

    public function __construct()
    {
        $this->debut_prev = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDelai(): ?int
    {
        return $this->delai;
    }

    public function setDelai(int $delai): self
    {
        $this->delai = $delai;

        return $this;
    }

    public function getDebutReel(): ?\DateTimeInterface
    {
        return $this->debut_reel;
    }

    public function setDebutReel(?\DateTimeInterface $debut_reel): self
    {
        $this->debut_reel = $debut_reel;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEstRealise(): ?bool
    {
        return $this->est_realise;
    }

    public function setEstRealise(?bool $est_realise): self
    {
        $this->est_realise = $est_realise;

        return $this;
    }

    public function getPlanning(): ?Planning
    {
        return $this->planning;
    }

    public function setPlanning(?Planning $planning): self
    {
        $this->planning = $planning;

        return $this;
    }

    public function getDelaiReel(): ?int
    {
        return $this->delai_reel;
    }

    public function setDelaiReel(int $delai_reel): self
    {
        $this->delai_reel = $delai_reel;

        return $this;
    }
}

templates/HTML/planning_gen.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{asset('css/CSS/planning_gen.css')}}">
    <link rel="stylesheet" href="{{asset('css/CSS/fontawesome/css/all.min.css')}}">
    <script src="{{asset('js/jquery-3.6.0.min.js')}}"></script>
    <title>{{ projet.nom }} - Planning général</title>
</head>
<body>
    <div id="header">
        <div id="click-menu">
            <i class="fa fa-bars close"></i>
        </div>

        <div id="logo">
            Archi - Tech
        </div>

        <a href="/profil" style="text-decoration:none;color:white;">
            <div id="infos-profil-icons">
                <i class="fa fa-user-circle fa-2x" id="icons"></i>
                <span id="nom">({{user.prenom}} {{user.nom}})</span>
            </div>
        </a>
    </div>

    <div id="section">
        <div id="side-menu">
            {% include "sidemenu.html.twig" %}
        </div>

        <div id="content">
            <div id="titre">
                Gestion du planning
            </div>

            <hr id="hr-content-titre">

            <div id="bande"></div>

            <div id="planning-gen">
                {% if user.poste == 'Architecte' and projet.estTermine == false %}
                    <div id="option-planning-add">
                        <a href="/projets/{{projet.id}}/planning/addTache"><button><i class="fa fa-plus"></i> Ajouter une tâche</button></a>

                        {{ form_start(form) }}
                            {{form_row(form.planning)}}

                            <input type="submit" value="Générer">
                        {{form_end(form)}}                     
                    </div>  
 
                {% endif %}
                

                {% if taches|length == 0 %}
                    <p id='zero'>Vous n'avez pas encore ajouté de tâches</p>
                {% else %}
                    <div id="entete">
                        <div class="colonne-intitule">Intitulé</div>
                        <div class="colonne-detail">Informations</div>
                        <div class="colonne-statut">Statut</div>                        
                    </div>

                    {% for tache in taches %}
                        <div id="tache{{tache.id}}">
                            <div class="lignes">
                                <div class="colonne-intitule">{{tache.intitule}}</div>
                                <div class="colonne-detail"><button class="detail" id="detail{{tache.id}}"> <span id="texte">Détails</span> <i class="fa fa-angle-down" id="angle"></i></button></div>
                                <div class="colonne-statut">{% if tache.estRealise %}Réalisée {% else %}Non réalisée{% endif %}</div>                           
                            </div>

                            <div id="infos-tache{{tache.id}}" class="infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Délai prévisionnel(jours)</div>
                                    <div class="info">{{ tache.delai }}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Date de début</div>
                                    <div class="info">{% if tache.debutReel %}{{tache.debutReel|date('d/m/Y')}}{% else %}---{% endif %}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Date de fin</div>
                                    <div class="info">{% if tache.dateFin %}{{tache.dateFin|date('d/m/Y')}}{% else %}---{% endif %}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Durée réelle(jours)</div>
                                    <div class="info">{% if tache.delaiReel %}{{tache.delaiReel}}{% else %}---{% endif %}</div>
                                </div>
                               
                            </div>

                            <script>
                                $('#infos-tache{{tache.id}}').css('display' , 'none');
                                $('#detail{{tache.id}}').click(function(){
                                    var visible = $('#infos-tache{{tache.id}}').hasClass('visible');
                                    if(visible == true)
                                    {
                                        $('#infos-tache{{tache.id}}').slideUp();
                                        $('#infos-tache{{tache.id}}').removeClass('visible');
                                    }
                                    else
                                    {
                                        $('#infos-tache{{tache.id}}').addClass('visible');
                                        $('#infos-tache{{tache.id}}').removeAttr('infos-tache');
                                        $('.infos-tache').slideUp();
                                        $('#infos-tache{{tache.id}}').slideToggle();
                                        $('#infos-tache{{tache.id}}').addClass('infos-tache');
                                    }
                                });
                            </script>
                        </div>                
                        <hr class="hr-planning">
                    {% endfor %}
                {% endif %}    
            </div>

            <div id="footer"><p><i class="fa fa-copyright"></i> Tout droits réservés , Oracle Logic Consulting SARL 2022</p></div>
        </div>
    </div>

    <script>
        $("#click-menu").click(function(){
            let visible = $("#side-menu").hasClass('visible');

            if(visible){
                $("#click-menu i").removeClass('fa-plus');
                $("#click-menu i").addClass('fa-bars');
                $("#side-menu").css('left', '-100%');
                $("#side-menu").removeClass('visible');
            }
            else{
                $("#click-menu i").removeClass('fa-bars');
                $("#click-menu i").addClass('fa-plus');
                $("#side-menu").css('left', '0');
                $("#side-menu").addClass('visible');
            }
        });
    </script>
</body>
</html>

templates/HTML/planning_taches_realisees.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{asset('css/CSS/planning_taches_realisees.css')}}">
    <link rel="stylesheet" href="{{asset('css/CSS/fontawesome/css/all.min.css')}}">
    <script src="{{asset('js/jquery-3.6.0.min.js')}}"></script>
    <title>{{ projet.nom }} - Tâches déjà réalisées</title>
</head>
<body>
    <div id="header">
        <div id="click-menu">
            <i class="fa fa-bars close"></i>
        </div>

        <div id="logo">
            Archi - Tech
        </div>

        <a href="/profil" style="text-decoration:none;color:white;">
            <div id="infos-profil-icons">
                <i class="fa fa-user-circle fa-2x" id="icons"></i>
                <span id="nom">({{user.prenom}} {{user.nom}})</span>
            </div>
        </a>
    </div>

    <div id="section">
        <div id="side-menu">
            {% include "sidemenu.html.twig" %}
        </div>

        <div id="content">
            <div id="titre">
                Les tâches déjà réalisées
            </div>

            <hr id="hr-content-titre">

            <div id="bande"></div>

            <div id="planning-gen">
                {% if taches|length == 0 %}
                    <p id='zero'>Vous n'avez pas encore terminé de tâches</p>
                {% else %}
                    <div id="entete">
                        <div class="colonne-intitule">Intitulé</div>
                        <div class="colonne-detail">Informations</div>
                        <div class="colonne-statut">Statut</div>
                    </div>

                    {% for tache in taches %}
                        {% if tache.estRealise == true %}
                        <div id="tache{{tache.id}}">
                            <div class="lignes">
                                <div class="colonne-intitule">{{tache.intitule}}</div>
                                <div class="colonne-detail"><button class="detail" id="detail{{tache.id}}"> <span id="texte">Détails</span> <i class="fa fa-angle-down" id="angle"></i></button></div>
                                <div class="colonne-statut">{% if tache.estRealise %}Réalisée {% else %}Non réalisée{% endif %}</div>                               
                            </div>

                            <div id="infos-tache{{tache.id}}" class="infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Délai prévisionnel(jours)</div>
                                    <div class="info">{{ tache.delai }}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Date de début</div>
                                    <div class="info">{% if tache.debutReel %}{{tache.debutReel|date('d/m/Y')}}{% else %}---{% endif %}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Date de fin</div>
                                    <div class="info">{% if tache.dateFin %}{{tache.dateFin|date('d/m/Y')}}{% else %}---{% endif %}</div>
                                </div>

                                <hr class="hr-infos-tache">

                                <div class="lignes-infos">
                                    <div class="libelle">Durée réelle(jours)</div>
                                    <div class="info">{% if tache.delaiReel %}{{tache.delaiReel}}{% else %}---{% endif %}</div>
                                </div>

                                {% if user.poste != 'Client' and tache.estRealise == false  and projet.estTermine == false %}
                                    <hr class="hr-infos-tache">

                                    <div class="option-modifier">
                                        <a href="/projets/{{projet.id}}/planning/tache/{{tache.id}}/edit"><button>Modifier</button></a>
                                    </div>
                                {% endif %}
                            </div>

                            <script>
                                $('#infos-tache{{tache.id}}').css('display' , 'none');
                                $('#detail{{tache.id}}').click(function(){
                                    var visible = $('#infos-tache{{tache.id}}').hasClass('visible');
                                    if(visible == true)
                                    {
                                        $('#infos-tache{{tache.id}}').slideUp();
                                        $('#infos-tache{{tache.id}}').removeClass('visible');
                                    }
                                    else
                                    {
                                        $('#infos-tache{{tache.id}}').addClass('visible');
                                        $('#infos-tache{{tache.id}}').removeAttr('infos-tache');
                                        $('.infos-tache').slideUp();
                                        $('#infos-tache{{tache.id}}').slideToggle();
                                        $('#infos-tache{{tache.id}}').addClass('infos-tache');
                                    }
                                });
                            </script>
                        </div>                
                        <hr class="hr-planning">
                        {% endif %}
                    {% endfor %}
                {% endif %}    
            </div> 

            <div id="footer"><p><i class="fa fa-copyright"></i> Tout droits réservés , Oracle Logic Consulting SARL 2022</p></div>
            
        </div>
    </div>

    <script>
        $("#click-menu").click(function(){
            let visible = $("#side-menu").hasClass('visible');

            if(visible){
                $("#click-menu i").removeClass('fa-plus');
                $("#click-menu i").addClass('fa-bars');
                $("#side-menu").css('left', '-100%');
                $("#side-menu").removeClass('visible');
            }
            else{
                $("#click-menu i").removeClass('fa-bars');
                $("#click-menu i").addClass('fa-plus');
                $("#side-menu").css('left', '0');
                $("#side-menu").addClass('visible');
            }
        });
    </script>
</body>
</html>